theme = "gruvbox"

[editor]
auto-format = false
auto-info = true
line-number = "relative"
cursorline = true
scrolloff = 5
color-modes = true
idle-timeout = 300
true-color = true
mouse = true
shell = ["fish"]
completion-trigger-len = 2
bufferline = "multiple"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.search]
smart-case = false
wrap-around = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.whitespace]
render = "all"

[editor.soft-wrap]
enable = true

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⤶"
tabpad = "."

[editor.statusline]
left = ["mode", "spinner", "file-name",] # file-path"]
center = ["version-control",] # "file-name"]
right = [
  "diagnostics",
  "file-encoding",
  "file-line-ending",
  "file-type",
  "position",
  "position-percentage",
  "selections",
]
# separator = "|";

[editor.indent-guides]
render = true

[keys.normal]
"X" = "extend_line_above"
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
esc = ["collapse_selection", "keep_primary_selection"]

[keys.insert]
"up" = "move_line_up"
"down" = "move_line_down"
"left" = "move_char_left"
"right" = "move_char_right"
