theme = "ayu_dark"

[editor]
auto-format = false
auto-info = true
line-number = "relative"
cursorline = true
scrolloff = 5
color-modes = true
idle-timeout = 400
true-color = true
mouse = true
shell = [ "zsh" ]

[editor.lsp]
display-messages = true

[editor.search]
smart-case = false
wrap-around = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.whitespace]
render = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⤶"
tabpad = "."

[editor.statusline]
left = [ "mode", "spinner", "file-name" ]
center = [ ]
right = [ "diagnostics", "file-encoding", "file-line-ending", "file-type", "position", "position-percentage", "selections" ]

[editor.indent-guides]
render = true

[keys.normal]
"X" = "extend_line_above"
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
