theme = "ayu_mirage"

[editor]
auto-format = false
auto-info = true
line-number = "relative"
# cursorline = true
scrolloff = 5
# color-modes = true
idle-timeout = 300
true-color = true
mouse = true
shell = [ "zsh" ]
auto-completion = true

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace]
render = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⤶"

[editor.lsp]
display-messages = true

[editor.file-picker]
hidden = false

[editor.search]
smart-case = false
wrap-around = true

# [editor.statusline]
# left = [ "mode" "spinner" "file-name" ]
# center = []
# right = [ "diagnostics" "file-encoding" "file-line-ending" "file-type" "position" "selections" ]

# [editor.indent-guides]
# render = true

[keys.normal]
"X" = "extend_line_above"
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
