theme = "gruvbox"

[editor]
auto-format = false
auto-info = true
line-number = "relative"
cursorline = true
scrolloff = 5
color-modes = true
idle-timeout = 300
true-color = true
mouse = true
shell = ["fish", "-c"]
completion-trigger-len = 2
bufferline = "multiple"
rulers = [80, 100]

[editor.lsp]
display-messages = true
display-inlay-hints = true
auto-signature-help = true

[editor.gutters]
layout = [
  "spacer",
  "diff",
  "diagnostics",
  "line-numbers",
  "spacer"
]

[editor.search]
smart-case = true
wrap-around = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
# git-ignore = false

[editor.whitespace]
render = "all"

[editor.soft-wrap]
enable = true

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⤶"
tabpad = "."

[editor.statusline]
left = [
  "mode",
  "separator",
  "spinner",
  "file-name",
  "file-modification-indicator"
]
center = [
  "version-control",
  "spacer",
  "separator",
  "file-base-name",
  "file-modification-indicator"
]
right = [
  "diagnostics",
  "workspace-diagnostics",
  "separator",
  "file-encoding",
  "file-type",
  "separator",
  "position",
  "position-percentage",
  "total-line-numbers",
  "separator",
  "file-line-ending",
  "selections",
]
# separator = ""
separator = "|"

[editor.indent-guides]
render = true
character = ""
# character = "┆" # defauly "|"

[keys.normal]
"X" = "extend_line_above"
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
esc = ["collapse_selection", "keep_primary_selection"]
y = "yank_main_selection_to_clipboard"
# p = ""

[keys.insert]
"up" = "move_line_up"
"down" = "move_line_down"
"left" = "move_char_left"
"right" = "move_char_right"

[keys.normal."+"]
c = ":run-shell-command cargo check"
b = ":run-shell-command cargo build"
r = ":run-shell-command cargo run"
