inherits = "gruvbox"

# transparent background
# "ui.background" = {}

"ui.cursor" = { fg = "white", bg = "light-red" }
# "ui.cursor.primary" = { modifiers = ["slow_blink", "dim"]}
"ui.cursor.match" = { bg = "white", modifiers = ["reversed"] }
"ui.cursorline.secondary" = "blue"

"comment" = { fg = "light-green", bg = "#282828", modifiers = ["italic", "dim"]}
