inherits = "gruvbox"

"ui.cursor" = { fg = "white", bg = "light-red" }
# "ui.cursor.primary" = { modifiers = ["slow_blink", "dim"]}
"ui.cursor.match" = {bg = "white", modifiers = ["reversed"]}

"ui.cursorline.secondary" = "blue"

