# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ohci_pci" "ehci_pci" "ahci" "usbhid" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "wl" ];
  boot.extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/60fc9d2e-3d04-4c63-aa95-40af048a76e3";
      fsType = "btrfs";
      options = [ "subvol=@root" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/60fc9d2e-3d04-4c63-aa95-40af048a76e3";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/srv" =
    { device = "/dev/disk/by-uuid/60fc9d2e-3d04-4c63-aa95-40af048a76e3";
      fsType = "btrfs";
      options = [ "subvol=@srv" ];
    };

  fileSystems."/opt" =
    { device = "/dev/disk/by-uuid/60fc9d2e-3d04-4c63-aa95-40af048a76e3";
      fsType = "btrfs";
      options = [ "subvol=@opt" ];
    };

  fileSystems."/tmp" =
    { device = "/dev/disk/by-uuid/60fc9d2e-3d04-4c63-aa95-40af048a76e3";
      fsType = "btrfs";
      options = [ "subvol=@tmp" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1111-78D8";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/e4d33d1d-6052-4422-8166-211b871215e2";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/var/lib/docker/btrfs" =
    { device = "/tmp/@srv/@root/var/lib/docker/btrfs";
      fsType = "none";
      options = [ "bind" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/344e444a-36ab-4552-bca0-e5b5e4488c3c"; }
    ];

}
