# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ohci_pci" "ehci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "wl" ];
  boot.extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/abfdc560-4832-4b90-882a-53970c75be34";
      fsType = "btrfs";
      options = [ "subvol=@root" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/abfdc560-4832-4b90-882a-53970c75be34";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/abfdc560-4832-4b90-882a-53970c75be34";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/srv" =
    { device = "/dev/disk/by-uuid/abfdc560-4832-4b90-882a-53970c75be34";
      fsType = "btrfs";
      options = [ "subvol=@srv" ];
    };

  fileSystems."/tmp" =
    { device = "/dev/disk/by-uuid/abfdc560-4832-4b90-882a-53970c75be34";
      fsType = "btrfs";
      options = [ "subvol=@tmp" ];
    };

  fileSystems."/opt" =
    { device = "/dev/disk/by-uuid/abfdc560-4832-4b90-882a-53970c75be34";
      fsType = "btrfs";
      options = [ "subvol=@opt" ];
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/abfdc560-4832-4b90-882a-53970c75be34";
      fsType = "btrfs";
      options = [ "subvol=@var" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1F30-ADF4";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/250157f4-8d32-474b-8b52-0301d6926f00"; }
    ];

}
