global:
  logging:
    - type: "stdout"
      level: "info"
      format: "human"

jobs:
# this job takes care of snapshot creation + pruning
  - name: snapjob
    type: snap
    filesystems: {
      "rpool<": true,
      "data<": true,
      "store<": true,
      }
    snapshotting:
      type: periodic
      interval: 15m
      prefix: zrepl_
    pruning:
      keep:
      # fade-out scheme for snapshots starting with `zrepl_`
      # - keep all created in the last hour
      # - then destroy snapshots such that we keep 24 each 1 hour apart
      # - then destroy snapshots such that we keep 14 each 1 day apart
      # - then destroy all older snapshots
      - type: grid
        grid: 1x1h(keep=all) | 24x1h | 14x1d
        regex: "^zrepl_.*"
      # keep all snapshots that don't have the `zrepl_` prefix
      - type: regex
        negate: true
        regex: "^zrepl_.*"

  - name: push_rpool_to_bck
    type: push
    connect:
      type: local
      listener_name: bck_sink_omni
      client_identity: omni
    filesystems: {
      "rpool<": true,
      "rpool/swap": false,
      }
    send:
      encrypted: false
    snapshotting:
      type: manual
    replication:
      protection:
        initial: guarantee_resumability
        incremental: guarantee_incremental
    pruning:
      keep_sender:
      - type: regex
        regex: ".*"
      # retain 
      keep_receiver:
      - type: grid
        grid: 1x1h(keep=all) | 24x1h | 360x1d
        regex: "^zrepl_.*"
      - type: regex
        negate: true
        regex: "^zrepl_.*"

  - name: bck_sink_omni
    type: sink
    root_fs: "backup/zrepl/omni"
    serve:
      type: local
      listener_name: bck_sink_omni

  - name: push_data_to_bck
    type: push
    connect:
      type: local
      listener_name: bck_sink_data
      client_identity: omni
    filesystems: {
      "data<": true,
      "data/iso": false,
      "data/export": false,
      }
    send:
      encrypted: false
    snapshotting:
      type: manual
    replication:
      protection:
        initial: guarantee_resumability
        incremental: guarantee_incremental
    pruning:
      keep_sender:
      - type: regex
        regex: ".*"
      keep_receiver:
      - type: grid
        grid: 1x1h(keep=all) | 24x1h | 360x1d
        regex: "^zrepl_.*"
      - type: regex
        negate: true
        regex: "^zrepl_.*"

  - name: bck_sink_data
    type: sink
    root_fs: "backup/zrepl/data"
    serve:
      type: local
      listener_name: bck_sink_data

  - name: push_store_to_bck
    type: push
    connect:
      type: local
      listener_name: bck_sink_store
      client_identity: omni
    filesystems: {
      "store<": true,
      "store/media/music<": false
      }
    send:
      encrypted: false
    snapshotting:
      type: manual
    replication:
      protection:
        initial: guarantee_resumability
        incremental: guarantee_incremental
    pruning:
      keep_sender:
      - type: regex
        regex: ".*"
      keep_receiver:
      - type: grid
        grid: 1x1h(keep=all) | 24x1h | 360x1d
        regex: "^zrepl_.*"
      - type: regex
        negate: true
        regex: "^zrepl_.*"

  - name: bck_sink_store
    type: sink
    root_fs: "backup/zrepl/store"
    serve:
      type: local
      listener_name: bck_sink_store
