# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/b44bf0be-d0e5-4711-8e9e-896fac64838f";
      fsType = "btrfs";
      options = [ "subvol=@root" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/b44bf0be-d0e5-4711-8e9e-896fac64838f";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/b44bf0be-d0e5-4711-8e9e-896fac64838f";
      fsType = "btrfs";
      options = [ "subvol=@var" ];
    };

  fileSystems."/srv" =
    { device = "/dev/disk/by-uuid/b44bf0be-d0e5-4711-8e9e-896fac64838f";
      fsType = "btrfs";
      options = [ "subvol=@srv" ];
    };

  fileSystems."/opt" =
    { device = "/dev/disk/by-uuid/b44bf0be-d0e5-4711-8e9e-896fac64838f";
      fsType = "btrfs";
      options = [ "subvol=@opt" ];
    };

  fileSystems."/tmp" =
    { device = "/dev/disk/by-uuid/b44bf0be-d0e5-4711-8e9e-896fac64838f";
      fsType = "btrfs";
      options = [ "subvol=@tmp" ];
    };

  fileSystems."/var/lib/docker/btrfs" =
    { device = "/tmp/@tmp/@var/lib/docker/btrfs//deleted";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/34d8df98-e664-4cb3-83d4-241d04564d86";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2CDD-5DB0";
      fsType = "vfat";
    };

  fileSystems."/home/lk/vm" =
    { device = "/dev/disk/by-uuid/806efee3-efbd-4236-b2c4-c9a4ad9c0c62";
      fsType = "btrfs";
      options = [ "subvol=@vm" ];
    };

  fileSystems."/home/lk/data" =
    { device = "/dev/disk/by-uuid/71bff5ad-3209-4d8f-8ead-65733cfb4b88";
      fsType = "btrfs";
      options = [ "subvol=@data" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/ac236b9f-1a37-4710-a3f7-6af2acecb56a"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
