theme = "gruvbox"

[editor]
scrolloff = 5
auto-completion = true
auto-format = true
true-color= true
line-number = "relative"
mouse = true
#auto-completion = true
auto-info = true
#auto-pairs = true
#true-color = true

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[editor.whitespace]
render = "all"
# or control each character
#[editor.whitespace.render]
#space = "all"
#tab = "all"
#newline = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"

#[editor-lsp]
#display-messages = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.search]
smart-case = true
wrap-around = true

# [editor.auto-pairs]
# true
