autoboot="true"
brand="bhyve"
zonename="ai"
zonepath="/zones/ai"

cdrom="/tank/iso/latest-nixos-gnome-x86_64-linux.iso"
ram="20G"
vcpus="6"

dns-domain="home.lan"
resolvers=[
  "1.1.1.1",
  "9.9.9.9",
]

acpi="on"
# xhci="on"
bootorder="cd"
ip-type="exclusive"
limitpriv="default"

[capped-memory]
# should match global "ram" key above
physical="20G"
swap="2G"

[[net]]
global-nic="e1000g0"
physical="ai0"
allowed-address="192.168.1.92/24"
defrouter="192.168.1.1"

[bootdisk]
blocksize="8K"
path="tank/vm/ai/root"
size="200G"
sparse="false"

[vnc]
enabled="on"
