autoboot="true"
brand="bhyve"
zonename="almasrv"
zonepath="/zones/almasrv"

cdrom="/tank/iso/AlmaLinux-9.4-x86_64-boot.iso"

ram="2G"
vcpus="1"

dns-domain="almasrv.local"
resolvers=[
  "192.168.1.93",
  "1.1.1.1",
  "9.9.9.9",
]

acpi="on"
# xhci="on"
bootorder="cd"
ip-type="exclusive"
limitpriv="default"

[capped-memory]
# should match global "ram" key above
physical="2G"
swap="2G"

[[net]]
global-nic="e1000g0"
physical="almasrv0"
allowed-address="192.168.1.83/24"
defrouter="192.168.1.1"

[bootdisk]
blocksize="8K"
path="tank/vm/almasrv/root"
size="20G"
sparse="false"

[vnc]
# needed for installation
enabled="on"
