autoboot="true"
brand="bhyve"
zonename="jelly"
zonepath="/zones/jelly"

cdrom="/tank/iso/latest-nixos-gnome-x86_64-linux.iso"
ram="2G"
vcpus="1"

dns-domain="jelly.local"
resolvers=[
  "1.1.1.1",
  "9.9.9.9",
]

acpi="on"
# xhci="on"
bootorder="cd"
ip-type="exclusive"
limitpriv="default"

[capped-memory]
# should match global "ram" key above
physical="2G"
swap="2G"

[[net]]
global-nic="e1000g0"
physical="jelly0"
allowed-address="192.168.1.90/24"
defrouter="192.168.1.1"

[bootdisk]
blocksize="8K"
path="rpool/vm/jelly/root"
size="20G"
sparse="false"

[vnc]
enabled="on"
