autoboot="true"
brand="bhyve"
zonename="kinoite"
zonepath="/zones/kinoite"

cdrom="/export/iso/Fedora-Kinoite-ostree-x86_64-40-1.14.iso"

ram="6G"
vcpus="2"

dns-domain="kinoite.local"
resolvers=[
  "1.1.1.1",
  "9.9.9.9",
]

acpi="on"
xhci="on"
type="windows"
bootorder="cd"
ip-type="exclusive"
limitpriv="default"

[capped-memory]
# should match global "ram" key above
physical="6G"
swap="2G"

[[net]]
global-nic="e1000g0"
physical="kinoite0"
allowed-address="192.168.1.89/24"
defrouter="192.168.1.1"

[bootdisk]
blocksize="8K"
path="rpool/vm/kinoite/root"
size="30G"
sparse="false"

[vnc]
# needed for installation
enabled="on"
unix="/tmp/vm.vnc"
