autoboot="false"
brand="bhyve"
zonename="kinoite"
zonepath="/zones/kinoite"

cdrom="/iso/Fedora-Kinoite-ostree-x86_64-39-1.5.iso"

ram="6G"
vcpus="2"

dns-domain="kinoite.local"
resolvers=[
  "1.1.1.1",
  "9.9.9.9",
]

acpi="on"
xhci="on"
bootorder="cd"
ip-type="exclusive"
limitpriv="default"

[capped-memory]
# should match global "ram" key above
physical="6G"
swap="2G"

[[net]]
global-nic="e1000g0"
physical="kinoite0"
allowed-address="192.168.1.90/24"
defrouter="192.168.1.1"

[bootdisk]
blocksize="8K"
path="rpool/vm/kinoite/root"
size="100G"
sparse="false"

[vnc]
# needed for installation
enabled="on"
