autoboot="true"
brand="pkgsrc"
zonename="latex"
zonepath="/zones/latex"

ip-type="exclusive"
resolvers=[
  "1.1.1.1",
]

[[net]]
global-nic="e1000g0"
physical="latex0"
allowed-address="192.168.1.74/24"
defrouter="192.168.1.1"

[[fs]]
dir="/config"
special="/home/lk/configs"
type="lofs"
options=["ro", "nodevices"]

[[fs]]
dir="/coding"
special="/coding"
type="lofs"
options=["rw", "nodevices"]
