autoboot="true"
brand="bhyve"
zonename="linux"
zonepath="/zones/linux"

cdrom="/data/iso/.iso"

ram="4G"
vcpus="2"

dns-domain="home.lan"
resolvers=[
  "192.168.1.104",
  "192.168.1.99",
  "1.1.1.1",
]

acpi="on"
xhci="on"
# type="windows"
bootorder="cd"
ip-type="exclusive"
limitpriv="default"

[capped-memory]
# should match global "ram" key above
physical="4G"
swap="2G"

[[net]]
global-nic="e1000g0"
physical="linux0"
allowed-address="192.168.1.83/24"
defrouter="192.168.1.1"

[bootdisk]
blocksize="8K"
path="tank/vm/linux/root"
size="30G"
sparse="false"

[vnc]
enabled="on"
# unix="/tmp/vm.vnc"
