autoboot="true"
brand="bhyve"
zonename="netbsd"
zonepath="/zones/netbsd"

cdrom="/tank/iso/NetBSD-10.0-amd64.iso"

# type="netbsd"

ram="2G"
vcpus="1"

dns-domain="netbsd.local"
resolvers=[
  "192.168.1.93",
  "1.1.1.1",
  "9.9.9.9",
]

acpi="on"
xhci="on"
bootorder="cd"
ip-type="exclusive"
limitpriv="default"

[capped-memory]
physical="2G"
swap="2G"

[[net]]
global-nic="e1000g0"
physical="netbsd0"
allowed-address="192.168.1.95/24"
defrouter="192.168.1.1"

[bootdisk]
blocksize="8K"
path="tank/vm/netbsd/root"
size="30G"
sparse="false"

[vnc]
enabled="on"
