autoboot="false"
brand="bhyve"
zonename="omni"
zonepath="/zones/omni"

cdrom="/data/iso/"

ram="3G"
vcpus="2"

dns-domain="home.lan"
resolvers=[
  "192.168.1.99",
  "1.1.1.1",
  "9.9.9.9",
]

acpi="on"
xhci="on"
bootorder="cd"
ip-type="exclusive"
limitpriv="default"

[capped-memory]
# should match global "ram" key above
physical="2G"
swap="2G"

[[net]]
global-nic="e1000g0"
physical="omni0"
allowed-address="192.168.1.98/24"
defrouter="192.168.1.1"

[bootdisk]
blocksize="8K"
path="tank/vm/omni/root"
size="30G"
sparse="true"

[[disk]]
blocksize="8K"
path="tank/vm_vol/omni"
size="30G"
sparse="true"

[vnc]
# needed for installation
enabled="on"
