autoboot="false"
brand="bhyve"
zonename="openbsd"
zonepath="/zones/openbsd"

cdrom="/export/iso/install75.iso"

type="openbsd"

ram="2G"
vcpus="2"

dns-domain="free.local"
resolvers=[
  "1.1.1.1",
  "9.9.9.9",
]

acpi="on"
xhci="on"
bootorder="cd"
ip-type="exclusive"
limitpriv="default"

[capped-memory]
# should match global "ram" key above
physical="2G"
swap="2G"

[[net]]
global-nic="e1000g0"
physical="openbsd0"
allowed-address="192.168.1.94/24"
defrouter="192.168.1.1"

[bootdisk]
blocksize="8K"
path="rpool/vm/openbsd/root"
size="50G"
sparse="false"

# [[fs]]
# dir="/config"
# special="/home/lk/configs"
# type="lofs"
# options=["ro", "nodevices"]

[vnc]
enabled="on"
