autoboot="true"
brand="sparse"
zonename="photodb"
zonepath="/zones/photodb"

ip-type="exclusive"
resolvers=[
  "1.1.1.1",
]

[[net]]
global-nic="e1000g0"
physical="photodb0"
allowed-address="192.168.1.76/24"
defrouter="192.168.1.1"
