autoboot="true"
brand="bhyve"
zonename="pihole"
zonepath="/zones/pihole"

cdrom="/export/iso/Fedora-Server-netinst-x86_64-40-1.14.iso"

ram="2G"
vcpus="1"

dns-domain="pihole.local"
resolvers=[
  "1.1.1.1",
  "9.9.9.9",
]

acpi="on"
xhci="on"
bootorder="cd"
ip-type="exclusive"
limitpriv="default"

[capped-memory]
physical="1G"
swap="1G"

[[net]]
global-nic="e1000g0"
physical="pihole0"
allowed-address="192.168.1.80/24"
defrouter="192.168.1.1"

[bootdisk]
blocksize="8K"
path="rpool/vm/pihole/root"
size="10G"
sparse="false"

[vnc]
# needed for installation
enabled="on"
