autoboot="true"
brand="bhyve"
zonename="pihole"
zonepath="/zones/pihole"

cdrom="/tank/iso/debian-12.10.0-amd64-netinst.iso"

ram="2G"
vcpus="1"

dns-domain="home.lan"
resolvers=[
  "1.1.1.1",
  "9.9.9.9",
]

acpi="on"
xhci="on"
bootorder="cd"
ip-type="exclusive"
limitpriv="default"

[capped-memory]
physical="1G"
swap="1G"

[[net]]
global-nic="e1000g0"
physical="pihole0"
allowed-address="192.168.1.99/24"
defrouter="192.168.1.1"

[bootdisk]
blocksize="8K"
path="tank/vm/pihole/root"
size="6G"
sparse="false"

[vnc]
enabled="on"
