autoboot="true"
brand="pkgsrc"
zonename="py"
zonepath="/zones/py"

ip-type="exclusive"
resolvers=[
  "192.168.1.93",
  "1.1.1.1"
]

[[net]]
global-nic="e1000g0"
physical="py0"
allowed-address="192.168.1.73/24"
defrouter="192.168.1.1"

[[fs]]
dir="/config"
special="/export/conf/configs"
type="lofs"
options=["ro", "nodevices"]

[[fs]]
dir="/coding"
special="/export/coding"
type="lofs"
options=["rw", "nodevices"]
