autoboot="true"
brand="lipkg"
zonename="rust"
zonepath="/zones/rust"

ip-type="exclusive"
resolvers=[
  "1.1.1.1",
]

[[net]]
global-nic="e1000g0"
physical="rust0"
allowed-address="192.168.1.72/24"
defrouter="192.168.1.1"

[[fs]]
dir="/config"
special="/home/lk/configs"
type="lofs"
options=["ro", "nodevices"]

[[fs]]
dir="/coding"
special="/coding"
type="lofs"
options=["rw", "nodevices"]
