autoboot="true"
brand="sparse"
zonename="samba"
zonepath="/zones/samba"

dns-domain="samba.local"
ip-type="exclusive"
resolvers=[
  "1.1.1.1",
  "9.9.9.9",
]

[[net]]
global-nic="e1000g0"
physical="samba0"
allowed-address="192.168.1.40/24"
defrouter="192.168.1.1"


[[dataset]]
name="rpool/coding"

[[fs]]
dir="/coding"
special="/coding"
type="lofs"
options=["rw", "nodevices"]
