autoboot="false"
brand="bhyve"
zonename="suse"
zonepath="/zones/suse"

cdrom="/tank/iso/agama-installer-Leap.x86_64-Leap.iso"

ram="5G"
vcpus="3"

dns-domain="suse.lan"
resolvers=[
  "192.168.1.99",
  "1.1.1.1",
  "9.9.9.9",
]

acpi="on"
xhci="on"
bootorder="cd"
ip-type="exclusive"
limitpriv="default"

[capped-memory]
# should match global "ram" key above
physical="5G"
swap="2G"

[[net]]
global-nic="e1000g0"
physical="suse0"
allowed-address="192.168.1.83/24"
defrouter="192.168.1.1"

[bootdisk]
blocksize="8K"
path="tank/vm/suse/root"
size="80G"
sparse="false"

[vnc]
enabled="on"
# unix="/tmp/vm.vnc"
