autoboot="false"
brand="bhyve"
zonename="ubuntu"
zonepath="/zones/ubuntu"

cdrom="/iso/lubuntu-23.10-desktop-amd64.iso"

ram="8G"
vcpus="4"

dns-domain="ubuntu.local"
resolvers=[
  "1.1.1.1",
  "9.9.9.9",
]

acpi="on"
xhci="on"
bootorder="cd"
ip-type="exclusive"
limitpriv="default"

[capped-memory]
# should match global "ram" key above
physical="8G"
swap="2G"

[[net]]
global-nic="e1000g0"
physical="ubuntu0"
allowed-address="192.168.1.89/24"
defrouter="192.168.1.1"

[bootdisk]
blocksize="8K"
path="rpool/vm/ubuntu/root"
size="100G"
sparse="false"

[vnc]
# needed for installation
enabled="on"
