autoboot="true"
brand="lipkg"
zonename="webui"
zonepath="/zones/webui"

ip-type="exclusive"
resolvers=[
  "192.168.1.93",
  "1.1.1.1"
]

[[net]]
global-nic="e1000g0"
physical="webui0"
allowed-address="192.168.1.73/24"
defrouter="192.168.1.1"
