autoboot="false"
brand="bhyve"
zonename="wintest"
zonepath="/zones/wintest"

cdrom=[
  "/tank/iso/Win11_24H2_Polish_x64.iso",
  "/tank/iso/virtio-win-0.1.262.iso",
]

type="windows"
extra="-w"

ram="6G"
vcpus="3"

dns-domain="home.lan"
resolvers=[
  "192.168.1.99",
  "1.1.1.1",
  "9.9.9.9",
]

acpi="off"
xhci="on"
bootorder="cd"
ip-type="exclusive"
limitpriv="default"

[capped-memory]
# should match global "ram" key above
physical="6G"
swap="4G"

[[net]]
global-nic="e1000g0"
physical="wintest0"
allowed-address="192.168.1.96/24"
defrouter="192.168.1.1"

[bootdisk]
blocksize="8K"
path="tank/vm/wintest/root"
size="150G"
sparse="true"

[vnc]
enabled="on"
