# Print an optspec for argparse to handle cmd's options that are independent of any subcommand.
function __fish_blackship_global_optspecs
	string join \n c/config= v/verbose h/help V/version
end

function __fish_blackship_needs_command
	# Figure out if the current invocation already has a command.
	set -l cmd (commandline -opc)
	set -e cmd[1]
	argparse -s (__fish_blackship_global_optspecs) -- $cmd 2>/dev/null
	or return
	if set -q argv[1]
		# Also print the command, so this can be used to figure out what it is.
		echo $argv[1]
		return 1
	end
	return 0
end

function __fish_blackship_using_subcommand
	set -l cmd (__fish_blackship_needs_command)
	test -z "$cmd"
	and return 1
	contains -- $cmd[1] $argv
end

complete -c blackship -n "__fish_blackship_needs_command" -s c -l config -d 'Configuration file path' -r -F
complete -c blackship -n "__fish_blackship_needs_command" -s v -l verbose -d 'Enable verbose output'
complete -c blackship -n "__fish_blackship_needs_command" -s h -l help -d 'Print help'
complete -c blackship -n "__fish_blackship_needs_command" -s V -l version -d 'Print version'
complete -c blackship -n "__fish_blackship_needs_command" -f -a "up" -d 'Start jails (respecting dependencies)'
complete -c blackship -n "__fish_blackship_needs_command" -f -a "down" -d 'Stop jails (in reverse dependency order)'
complete -c blackship -n "__fish_blackship_needs_command" -f -a "restart" -d 'Restart jails'
complete -c blackship -n "__fish_blackship_needs_command" -f -a "ps" -d 'List jail status'
complete -c blackship -n "__fish_blackship_needs_command" -f -a "check" -d 'Validate configuration'
complete -c blackship -n "__fish_blackship_needs_command" -f -a "setup" -d 'System setup (PF firewall anchor, etc.)'
complete -c blackship -n "__fish_blackship_needs_command" -f -a "init" -d 'Initialize a new Jailfile in the current directory'
complete -c blackship -n "__fish_blackship_needs_command" -f -a "armada" -d 'Orchestrate multiple jails (like docker-compose)'
complete -c blackship -n "__fish_blackship_needs_command" -f -a "exec" -d 'Execute a command in a running jail'
complete -c blackship -n "__fish_blackship_needs_command" -f -a "run" -d 'Run a command in a new ephemeral jail (always cleans up when command exits)'
complete -c blackship -n "__fish_blackship_needs_command" -f -a "cp" -d 'Copy files between host and jail'
complete -c blackship -n "__fish_blackship_needs_command" -f -a "rm" -d 'Remove/destroy jails'
complete -c blackship -n "__fish_blackship_needs_command" -f -a "console" -d 'Open an interactive console in a running jail'
complete -c blackship -n "__fish_blackship_needs_command" -f -a "bootstrap" -d 'Bootstrap a FreeBSD release for jail creation'
complete -c blackship -n "__fish_blackship_needs_command" -f -a "releases" -d 'List or manage releases'
complete -c blackship -n "__fish_blackship_needs_command" -f -a "network" -d 'Network management'
complete -c blackship -n "__fish_blackship_needs_command" -f -a "health" -d 'Health check status and monitoring'
complete -c blackship -n "__fish_blackship_needs_command" -f -a "build" -d 'Build a jail from a Jailfile'
complete -c blackship -n "__fish_blackship_needs_command" -f -a "template" -d 'Template management'
complete -c blackship -n "__fish_blackship_needs_command" -f -a "expose" -d 'Expose a jail port to the host'
complete -c blackship -n "__fish_blackship_needs_command" -f -a "ports" -d 'List exposed ports'
complete -c blackship -n "__fish_blackship_needs_command" -f -a "unexpose" -d 'Remove all port forwards for a jail'
complete -c blackship -n "__fish_blackship_needs_command" -f -a "cleanup" -d 'Clean up a failed jail (remove leftover resources)'
complete -c blackship -n "__fish_blackship_needs_command" -f -a "export" -d 'Export a jail to an archive'
complete -c blackship -n "__fish_blackship_needs_command" -f -a "import" -d 'Import a jail from an archive'
complete -c blackship -n "__fish_blackship_needs_command" -f -a "snapshot" -d 'Manage jail snapshots'
complete -c blackship -n "__fish_blackship_needs_command" -f -a "clone" -d 'Clone a jail from a snapshot'
complete -c blackship -n "__fish_blackship_needs_command" -f -a "completion" -d 'Generate shell completion scripts'
complete -c blackship -n "__fish_blackship_needs_command" -f -a "supervise" -d 'Start the Warden supervisor to monitor and auto-restart jails'
complete -c blackship -n "__fish_blackship_needs_command" -f -a "logs" -d 'Tail logs from a running jail'
complete -c blackship -n "__fish_blackship_needs_command" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c blackship -n "__fish_blackship_using_subcommand up" -l all -d 'Start all jails (required if no jail specified)'
complete -c blackship -n "__fish_blackship_using_subcommand up" -l dry-run -d 'Show what would be done without making changes'
complete -c blackship -n "__fish_blackship_using_subcommand up" -s h -l help -d 'Print help'
complete -c blackship -n "__fish_blackship_using_subcommand up" -s V -l version -d 'Print version'
complete -c blackship -n "__fish_blackship_using_subcommand down" -l all -d 'Stop all jails (required if no jail specified)'
complete -c blackship -n "__fish_blackship_using_subcommand down" -l dry-run -d 'Show what would be done without making changes'
complete -c blackship -n "__fish_blackship_using_subcommand down" -s h -l help -d 'Print help'
complete -c blackship -n "__fish_blackship_using_subcommand down" -s V -l version -d 'Print version'
complete -c blackship -n "__fish_blackship_using_subcommand restart" -l all -d 'Restart all jails (required if no jail specified)'
complete -c blackship -n "__fish_blackship_using_subcommand restart" -l dry-run -d 'Show what would be done without making changes'
complete -c blackship -n "__fish_blackship_using_subcommand restart" -s h -l help -d 'Print help'
complete -c blackship -n "__fish_blackship_using_subcommand restart" -s V -l version -d 'Print version'
complete -c blackship -n "__fish_blackship_using_subcommand ps" -l json -d 'Output in JSON format'
complete -c blackship -n "__fish_blackship_using_subcommand ps" -s h -l help -d 'Print help'
complete -c blackship -n "__fish_blackship_using_subcommand ps" -s V -l version -d 'Print version'
complete -c blackship -n "__fish_blackship_using_subcommand check" -s h -l help -d 'Print help'
complete -c blackship -n "__fish_blackship_using_subcommand check" -s V -l version -d 'Print version'
complete -c blackship -n "__fish_blackship_using_subcommand setup" -s h -l help -d 'Print help'
complete -c blackship -n "__fish_blackship_using_subcommand setup" -s V -l version -d 'Print version'
complete -c blackship -n "__fish_blackship_using_subcommand init" -s f -l file -d 'Output file name' -r -F
complete -c blackship -n "__fish_blackship_using_subcommand init" -s r -l release -d 'Base FreeBSD release' -r
complete -c blackship -n "__fish_blackship_using_subcommand init" -l toml -d 'Use TOML format instead of Dockerfile-like format'
complete -c blackship -n "__fish_blackship_using_subcommand init" -s y -l force -d 'Overwrite existing file'
complete -c blackship -n "__fish_blackship_using_subcommand init" -s h -l help -d 'Print help'
complete -c blackship -n "__fish_blackship_using_subcommand init" -s V -l version -d 'Print version'
complete -c blackship -n "__fish_blackship_using_subcommand armada; and not __fish_seen_subcommand_from init up down build ps config help" -s f -l file -d 'Configuration files (can specify multiple, merged in order)' -r -F
complete -c blackship -n "__fish_blackship_using_subcommand armada; and not __fish_seen_subcommand_from init up down build ps config help" -s h -l help -d 'Print help'
complete -c blackship -n "__fish_blackship_using_subcommand armada; and not __fish_seen_subcommand_from init up down build ps config help" -s V -l version -d 'Print version'
complete -c blackship -n "__fish_blackship_using_subcommand armada; and not __fish_seen_subcommand_from init up down build ps config help" -f -a "init" -d 'Initialize a new blackship.toml'
complete -c blackship -n "__fish_blackship_using_subcommand armada; and not __fish_seen_subcommand_from init up down build ps config help" -f -a "up" -d 'Start all jails (auto-builds if needed)'
complete -c blackship -n "__fish_blackship_using_subcommand armada; and not __fish_seen_subcommand_from init up down build ps config help" -f -a "down" -d 'Stop all jails'
complete -c blackship -n "__fish_blackship_using_subcommand armada; and not __fish_seen_subcommand_from init up down build ps config help" -f -a "build" -d 'Build jail images from Jailfiles'
complete -c blackship -n "__fish_blackship_using_subcommand armada; and not __fish_seen_subcommand_from init up down build ps config help" -f -a "ps" -d 'Show status of all jails'
complete -c blackship -n "__fish_blackship_using_subcommand armada; and not __fish_seen_subcommand_from init up down build ps config help" -f -a "config" -d 'Validate and show configuration'
complete -c blackship -n "__fish_blackship_using_subcommand armada; and not __fish_seen_subcommand_from init up down build ps config help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c blackship -n "__fish_blackship_using_subcommand armada; and __fish_seen_subcommand_from init" -s f -l file -d 'Output file name' -r -F
complete -c blackship -n "__fish_blackship_using_subcommand armada; and __fish_seen_subcommand_from init" -s y -l force -d 'Overwrite existing file'
complete -c blackship -n "__fish_blackship_using_subcommand armada; and __fish_seen_subcommand_from init" -s h -l help -d 'Print help'
complete -c blackship -n "__fish_blackship_using_subcommand armada; and __fish_seen_subcommand_from init" -s V -l version -d 'Print version'
complete -c blackship -n "__fish_blackship_using_subcommand armada; and __fish_seen_subcommand_from up" -s d -l detach -d 'Run in background (warden mode)'
complete -c blackship -n "__fish_blackship_using_subcommand armada; and __fish_seen_subcommand_from up" -l build -d 'Force rebuild even if jail exists'
complete -c blackship -n "__fish_blackship_using_subcommand armada; and __fish_seen_subcommand_from up" -l no-build -d 'Don\'t build, fail if jail doesn\'t exist'
complete -c blackship -n "__fish_blackship_using_subcommand armada; and __fish_seen_subcommand_from up" -l dry-run -d 'Show what would be done without making changes'
complete -c blackship -n "__fish_blackship_using_subcommand armada; and __fish_seen_subcommand_from up" -s h -l help -d 'Print help'
complete -c blackship -n "__fish_blackship_using_subcommand armada; and __fish_seen_subcommand_from up" -s V -l version -d 'Print version'
complete -c blackship -n "__fish_blackship_using_subcommand armada; and __fish_seen_subcommand_from down" -l dry-run -d 'Show what would be done without making changes'
complete -c blackship -n "__fish_blackship_using_subcommand armada; and __fish_seen_subcommand_from down" -s h -l help -d 'Print help'
complete -c blackship -n "__fish_blackship_using_subcommand armada; and __fish_seen_subcommand_from down" -s V -l version -d 'Print version'
complete -c blackship -n "__fish_blackship_using_subcommand armada; and __fish_seen_subcommand_from build" -l dry-run -d 'Show what would be done without making changes'
complete -c blackship -n "__fish_blackship_using_subcommand armada; and __fish_seen_subcommand_from build" -s h -l help -d 'Print help'
complete -c blackship -n "__fish_blackship_using_subcommand armada; and __fish_seen_subcommand_from build" -s V -l version -d 'Print version'
complete -c blackship -n "__fish_blackship_using_subcommand armada; and __fish_seen_subcommand_from ps" -l json -d 'Output in JSON format'
complete -c blackship -n "__fish_blackship_using_subcommand armada; and __fish_seen_subcommand_from ps" -s h -l help -d 'Print help'
complete -c blackship -n "__fish_blackship_using_subcommand armada; and __fish_seen_subcommand_from ps" -s V -l version -d 'Print version'
complete -c blackship -n "__fish_blackship_using_subcommand armada; and __fish_seen_subcommand_from config" -l show -d 'Show resolved (merged) configuration'
complete -c blackship -n "__fish_blackship_using_subcommand armada; and __fish_seen_subcommand_from config" -s h -l help -d 'Print help'
complete -c blackship -n "__fish_blackship_using_subcommand armada; and __fish_seen_subcommand_from config" -s V -l version -d 'Print version'
complete -c blackship -n "__fish_blackship_using_subcommand armada; and __fish_seen_subcommand_from help" -f -a "init" -d 'Initialize a new blackship.toml'
complete -c blackship -n "__fish_blackship_using_subcommand armada; and __fish_seen_subcommand_from help" -f -a "up" -d 'Start all jails (auto-builds if needed)'
complete -c blackship -n "__fish_blackship_using_subcommand armada; and __fish_seen_subcommand_from help" -f -a "down" -d 'Stop all jails'
complete -c blackship -n "__fish_blackship_using_subcommand armada; and __fish_seen_subcommand_from help" -f -a "build" -d 'Build jail images from Jailfiles'
complete -c blackship -n "__fish_blackship_using_subcommand armada; and __fish_seen_subcommand_from help" -f -a "ps" -d 'Show status of all jails'
complete -c blackship -n "__fish_blackship_using_subcommand armada; and __fish_seen_subcommand_from help" -f -a "config" -d 'Validate and show configuration'
complete -c blackship -n "__fish_blackship_using_subcommand armada; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c blackship -n "__fish_blackship_using_subcommand exec" -s u -l user -d 'User to run as' -r
complete -c blackship -n "__fish_blackship_using_subcommand exec" -s w -l workdir -d 'Working directory inside the jail' -r
complete -c blackship -n "__fish_blackship_using_subcommand exec" -s e -l env -d 'Environment variables (KEY=VALUE format, can be repeated)' -r
complete -c blackship -n "__fish_blackship_using_subcommand exec" -s h -l help -d 'Print help'
complete -c blackship -n "__fish_blackship_using_subcommand exec" -s V -l version -d 'Print version'
complete -c blackship -n "__fish_blackship_using_subcommand run" -l name -d 'Jail name' -r
complete -c blackship -n "__fish_blackship_using_subcommand run" -l release -d 'FreeBSD release to use (e.g., 15.0-RELEASE)' -r
complete -c blackship -n "__fish_blackship_using_subcommand run" -l network -d 'Network to attach to' -r
complete -c blackship -n "__fish_blackship_using_subcommand run" -s d -l detach -d 'Run in background (detached mode) - jail persists until removed with \'blackship rm\''
complete -c blackship -n "__fish_blackship_using_subcommand run" -s h -l help -d 'Print help'
complete -c blackship -n "__fish_blackship_using_subcommand run" -s V -l version -d 'Print version'
complete -c blackship -n "__fish_blackship_using_subcommand cp" -s p -l preserve -d 'Preserve file attributes'
complete -c blackship -n "__fish_blackship_using_subcommand cp" -s h -l help -d 'Print help'
complete -c blackship -n "__fish_blackship_using_subcommand cp" -s V -l version -d 'Print version'
complete -c blackship -n "__fish_blackship_using_subcommand rm" -s f -l force -d 'Force removal even if jail is running'
complete -c blackship -n "__fish_blackship_using_subcommand rm" -l volumes -d 'Remove associated ZFS datasets'
complete -c blackship -n "__fish_blackship_using_subcommand rm" -s h -l help -d 'Print help'
complete -c blackship -n "__fish_blackship_using_subcommand rm" -s V -l version -d 'Print version'
complete -c blackship -n "__fish_blackship_using_subcommand console" -s u -l user -d 'User to run as' -r
complete -c blackship -n "__fish_blackship_using_subcommand console" -s h -l help -d 'Print help'
complete -c blackship -n "__fish_blackship_using_subcommand console" -s V -l version -d 'Print version'
complete -c blackship -n "__fish_blackship_using_subcommand bootstrap" -s a -l archives -d 'Archives to download (default: base)' -r
complete -c blackship -n "__fish_blackship_using_subcommand bootstrap" -s f -l force -d 'Force re-download even if release exists'
complete -c blackship -n "__fish_blackship_using_subcommand bootstrap" -s h -l help -d 'Print help'
complete -c blackship -n "__fish_blackship_using_subcommand bootstrap" -s V -l version -d 'Print version'
complete -c blackship -n "__fish_blackship_using_subcommand releases; and not __fish_seen_subcommand_from list delete verify help" -l json -d 'Output in JSON format (for list action)'
complete -c blackship -n "__fish_blackship_using_subcommand releases; and not __fish_seen_subcommand_from list delete verify help" -s h -l help -d 'Print help'
complete -c blackship -n "__fish_blackship_using_subcommand releases; and not __fish_seen_subcommand_from list delete verify help" -s V -l version -d 'Print version'
complete -c blackship -n "__fish_blackship_using_subcommand releases; and not __fish_seen_subcommand_from list delete verify help" -f -a "list" -d 'List all bootstrapped releases (default)'
complete -c blackship -n "__fish_blackship_using_subcommand releases; and not __fish_seen_subcommand_from list delete verify help" -f -a "delete" -d 'Delete a bootstrapped release'
complete -c blackship -n "__fish_blackship_using_subcommand releases; and not __fish_seen_subcommand_from list delete verify help" -f -a "verify" -d 'Verify a bootstrapped release'
complete -c blackship -n "__fish_blackship_using_subcommand releases; and not __fish_seen_subcommand_from list delete verify help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c blackship -n "__fish_blackship_using_subcommand releases; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c blackship -n "__fish_blackship_using_subcommand releases; and __fish_seen_subcommand_from list" -s V -l version -d 'Print version'
complete -c blackship -n "__fish_blackship_using_subcommand releases; and __fish_seen_subcommand_from delete" -s h -l help -d 'Print help'
complete -c blackship -n "__fish_blackship_using_subcommand releases; and __fish_seen_subcommand_from delete" -s V -l version -d 'Print version'
complete -c blackship -n "__fish_blackship_using_subcommand releases; and __fish_seen_subcommand_from verify" -s h -l help -d 'Print help'
complete -c blackship -n "__fish_blackship_using_subcommand releases; and __fish_seen_subcommand_from verify" -s V -l version -d 'Print version'
complete -c blackship -n "__fish_blackship_using_subcommand releases; and __fish_seen_subcommand_from help" -f -a "list" -d 'List all bootstrapped releases (default)'
complete -c blackship -n "__fish_blackship_using_subcommand releases; and __fish_seen_subcommand_from help" -f -a "delete" -d 'Delete a bootstrapped release'
complete -c blackship -n "__fish_blackship_using_subcommand releases; and __fish_seen_subcommand_from help" -f -a "verify" -d 'Verify a bootstrapped release'
complete -c blackship -n "__fish_blackship_using_subcommand releases; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c blackship -n "__fish_blackship_using_subcommand network; and not __fish_seen_subcommand_from create destroy list attach detach help" -s h -l help -d 'Print help'
complete -c blackship -n "__fish_blackship_using_subcommand network; and not __fish_seen_subcommand_from create destroy list attach detach help" -s V -l version -d 'Print version'
complete -c blackship -n "__fish_blackship_using_subcommand network; and not __fish_seen_subcommand_from create destroy list attach detach help" -f -a "create" -d 'Create a new network'
complete -c blackship -n "__fish_blackship_using_subcommand network; and not __fish_seen_subcommand_from create destroy list attach detach help" -f -a "destroy" -d 'Destroy a network'
complete -c blackship -n "__fish_blackship_using_subcommand network; and not __fish_seen_subcommand_from create destroy list attach detach help" -f -a "list" -d 'List all networks'
complete -c blackship -n "__fish_blackship_using_subcommand network; and not __fish_seen_subcommand_from create destroy list attach detach help" -f -a "attach" -d 'Attach a jail to a network'
complete -c blackship -n "__fish_blackship_using_subcommand network; and not __fish_seen_subcommand_from create destroy list attach detach help" -f -a "detach" -d 'Detach a jail from a network'
complete -c blackship -n "__fish_blackship_using_subcommand network; and not __fish_seen_subcommand_from create destroy list attach detach help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c blackship -n "__fish_blackship_using_subcommand network; and __fish_seen_subcommand_from create" -s s -l subnet -d 'Subnet in CIDR notation (e.g., 10.0.1.0/24)' -r
complete -c blackship -n "__fish_blackship_using_subcommand network; and __fish_seen_subcommand_from create" -s g -l gateway -d 'Gateway address (defaults to first usable in subnet)' -r
complete -c blackship -n "__fish_blackship_using_subcommand network; and __fish_seen_subcommand_from create" -s b -l bridge -d 'Bridge interface name (defaults to blackship0)' -r
complete -c blackship -n "__fish_blackship_using_subcommand network; and __fish_seen_subcommand_from create" -s h -l help -d 'Print help'
complete -c blackship -n "__fish_blackship_using_subcommand network; and __fish_seen_subcommand_from create" -s V -l version -d 'Print version'
complete -c blackship -n "__fish_blackship_using_subcommand network; and __fish_seen_subcommand_from destroy" -s f -l force -d 'Force destruction even if jails are attached'
complete -c blackship -n "__fish_blackship_using_subcommand network; and __fish_seen_subcommand_from destroy" -s h -l help -d 'Print help'
complete -c blackship -n "__fish_blackship_using_subcommand network; and __fish_seen_subcommand_from destroy" -s V -l version -d 'Print version'
complete -c blackship -n "__fish_blackship_using_subcommand network; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c blackship -n "__fish_blackship_using_subcommand network; and __fish_seen_subcommand_from list" -s V -l version -d 'Print version'
complete -c blackship -n "__fish_blackship_using_subcommand network; and __fish_seen_subcommand_from attach" -s i -l ip -d 'IP address (auto-assigned if not specified)' -r
complete -c blackship -n "__fish_blackship_using_subcommand network; and __fish_seen_subcommand_from attach" -s h -l help -d 'Print help'
complete -c blackship -n "__fish_blackship_using_subcommand network; and __fish_seen_subcommand_from attach" -s V -l version -d 'Print version'
complete -c blackship -n "__fish_blackship_using_subcommand network; and __fish_seen_subcommand_from detach" -s h -l help -d 'Print help'
complete -c blackship -n "__fish_blackship_using_subcommand network; and __fish_seen_subcommand_from detach" -s V -l version -d 'Print version'
complete -c blackship -n "__fish_blackship_using_subcommand network; and __fish_seen_subcommand_from help" -f -a "create" -d 'Create a new network'
complete -c blackship -n "__fish_blackship_using_subcommand network; and __fish_seen_subcommand_from help" -f -a "destroy" -d 'Destroy a network'
complete -c blackship -n "__fish_blackship_using_subcommand network; and __fish_seen_subcommand_from help" -f -a "list" -d 'List all networks'
complete -c blackship -n "__fish_blackship_using_subcommand network; and __fish_seen_subcommand_from help" -f -a "attach" -d 'Attach a jail to a network'
complete -c blackship -n "__fish_blackship_using_subcommand network; and __fish_seen_subcommand_from help" -f -a "detach" -d 'Detach a jail from a network'
complete -c blackship -n "__fish_blackship_using_subcommand network; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c blackship -n "__fish_blackship_using_subcommand health" -s i -l interval -d 'Update interval in seconds (for watch mode)' -r
complete -c blackship -n "__fish_blackship_using_subcommand health" -s w -l watch -d 'Watch mode - continuously monitor health'
complete -c blackship -n "__fish_blackship_using_subcommand health" -l json -d 'Output in JSON format'
complete -c blackship -n "__fish_blackship_using_subcommand health" -s h -l help -d 'Print help'
complete -c blackship -n "__fish_blackship_using_subcommand health" -s V -l version -d 'Print version'
complete -c blackship -n "__fish_blackship_using_subcommand build" -s f -l file -d 'Path to Jailfile (default: ./Jailfile)' -r -F
complete -c blackship -n "__fish_blackship_using_subcommand build" -s n -l name -d 'Jail name (overrides metadata name)' -r
complete -c blackship -n "__fish_blackship_using_subcommand build" -l build-arg -d 'Build arguments (KEY=VALUE)' -r
complete -c blackship -n "__fish_blackship_using_subcommand build" -s c -l context -d 'Build context directory (default: directory containing Jailfile)' -r -F
complete -c blackship -n "__fish_blackship_using_subcommand build" -l dry-run -d 'Don\'t execute, just show what would be done'
complete -c blackship -n "__fish_blackship_using_subcommand build" -s h -l help -d 'Print help'
complete -c blackship -n "__fish_blackship_using_subcommand build" -s V -l version -d 'Print version'
complete -c blackship -n "__fish_blackship_using_subcommand template; and not __fish_seen_subcommand_from list inspect validate help" -s h -l help -d 'Print help'
complete -c blackship -n "__fish_blackship_using_subcommand template; and not __fish_seen_subcommand_from list inspect validate help" -s V -l version -d 'Print version'
complete -c blackship -n "__fish_blackship_using_subcommand template; and not __fish_seen_subcommand_from list inspect validate help" -f -a "list" -d 'List available templates'
complete -c blackship -n "__fish_blackship_using_subcommand template; and not __fish_seen_subcommand_from list inspect validate help" -f -a "inspect" -d 'Inspect a template or Jailfile'
complete -c blackship -n "__fish_blackship_using_subcommand template; and not __fish_seen_subcommand_from list inspect validate help" -f -a "validate" -d 'Validate a Jailfile'
complete -c blackship -n "__fish_blackship_using_subcommand template; and not __fish_seen_subcommand_from list inspect validate help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c blackship -n "__fish_blackship_using_subcommand template; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c blackship -n "__fish_blackship_using_subcommand template; and __fish_seen_subcommand_from list" -s V -l version -d 'Print version'
complete -c blackship -n "__fish_blackship_using_subcommand template; and __fish_seen_subcommand_from inspect" -s h -l help -d 'Print help'
complete -c blackship -n "__fish_blackship_using_subcommand template; and __fish_seen_subcommand_from inspect" -s V -l version -d 'Print version'
complete -c blackship -n "__fish_blackship_using_subcommand template; and __fish_seen_subcommand_from validate" -s h -l help -d 'Print help'
complete -c blackship -n "__fish_blackship_using_subcommand template; and __fish_seen_subcommand_from validate" -s V -l version -d 'Print version'
complete -c blackship -n "__fish_blackship_using_subcommand template; and __fish_seen_subcommand_from help" -f -a "list" -d 'List available templates'
complete -c blackship -n "__fish_blackship_using_subcommand template; and __fish_seen_subcommand_from help" -f -a "inspect" -d 'Inspect a template or Jailfile'
complete -c blackship -n "__fish_blackship_using_subcommand template; and __fish_seen_subcommand_from help" -f -a "validate" -d 'Validate a Jailfile'
complete -c blackship -n "__fish_blackship_using_subcommand template; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c blackship -n "__fish_blackship_using_subcommand expose" -s p -l port -d 'External port (host-side)' -r
complete -c blackship -n "__fish_blackship_using_subcommand expose" -s i -l internal -d 'Internal port (jail-side, defaults to external port)' -r
complete -c blackship -n "__fish_blackship_using_subcommand expose" -l proto -d 'Protocol (tcp or udp)' -r
complete -c blackship -n "__fish_blackship_using_subcommand expose" -s I -l bind-ip -d 'Bind to specific host IP (defaults to all interfaces)' -r
complete -c blackship -n "__fish_blackship_using_subcommand expose" -s h -l help -d 'Print help'
complete -c blackship -n "__fish_blackship_using_subcommand expose" -s V -l version -d 'Print version'
complete -c blackship -n "__fish_blackship_using_subcommand ports" -s h -l help -d 'Print help'
complete -c blackship -n "__fish_blackship_using_subcommand ports" -s V -l version -d 'Print version'
complete -c blackship -n "__fish_blackship_using_subcommand unexpose" -s h -l help -d 'Print help'
complete -c blackship -n "__fish_blackship_using_subcommand unexpose" -s V -l version -d 'Print version'
complete -c blackship -n "__fish_blackship_using_subcommand cleanup" -s f -l force -d 'Force cleanup even if errors occur'
complete -c blackship -n "__fish_blackship_using_subcommand cleanup" -s h -l help -d 'Print help'
complete -c blackship -n "__fish_blackship_using_subcommand cleanup" -s V -l version -d 'Print version'
complete -c blackship -n "__fish_blackship_using_subcommand export" -s o -l output -d 'Output file path (default: <jail>.tar.zst)' -r -F
complete -c blackship -n "__fish_blackship_using_subcommand export" -l zfs-send -d 'Use ZFS send for faster export (requires ZFS)'
complete -c blackship -n "__fish_blackship_using_subcommand export" -s h -l help -d 'Print help'
complete -c blackship -n "__fish_blackship_using_subcommand export" -s V -l version -d 'Print version'
complete -c blackship -n "__fish_blackship_using_subcommand import" -s n -l name -d 'Name for the imported jail (default: original name)' -r
complete -c blackship -n "__fish_blackship_using_subcommand import" -l force -d 'Overwrite existing jail'
complete -c blackship -n "__fish_blackship_using_subcommand import" -s h -l help -d 'Print help'
complete -c blackship -n "__fish_blackship_using_subcommand import" -s V -l version -d 'Print version'
complete -c blackship -n "__fish_blackship_using_subcommand snapshot; and not __fish_seen_subcommand_from create list rollback delete help" -s h -l help -d 'Print help'
complete -c blackship -n "__fish_blackship_using_subcommand snapshot; and not __fish_seen_subcommand_from create list rollback delete help" -s V -l version -d 'Print version'
complete -c blackship -n "__fish_blackship_using_subcommand snapshot; and not __fish_seen_subcommand_from create list rollback delete help" -f -a "create" -d 'Create a snapshot of a jail'
complete -c blackship -n "__fish_blackship_using_subcommand snapshot; and not __fish_seen_subcommand_from create list rollback delete help" -f -a "list" -d 'List snapshots for a jail'
complete -c blackship -n "__fish_blackship_using_subcommand snapshot; and not __fish_seen_subcommand_from create list rollback delete help" -f -a "rollback" -d 'Rollback a jail to a snapshot'
complete -c blackship -n "__fish_blackship_using_subcommand snapshot; and not __fish_seen_subcommand_from create list rollback delete help" -f -a "delete" -d 'Delete a snapshot'
complete -c blackship -n "__fish_blackship_using_subcommand snapshot; and not __fish_seen_subcommand_from create list rollback delete help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c blackship -n "__fish_blackship_using_subcommand snapshot; and __fish_seen_subcommand_from create" -s h -l help -d 'Print help'
complete -c blackship -n "__fish_blackship_using_subcommand snapshot; and __fish_seen_subcommand_from create" -s V -l version -d 'Print version'
complete -c blackship -n "__fish_blackship_using_subcommand snapshot; and __fish_seen_subcommand_from list" -l json -d 'Output in JSON format'
complete -c blackship -n "__fish_blackship_using_subcommand snapshot; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c blackship -n "__fish_blackship_using_subcommand snapshot; and __fish_seen_subcommand_from list" -s V -l version -d 'Print version'
complete -c blackship -n "__fish_blackship_using_subcommand snapshot; and __fish_seen_subcommand_from rollback" -s f -l force -d 'Force rollback, destroying newer snapshots'
complete -c blackship -n "__fish_blackship_using_subcommand snapshot; and __fish_seen_subcommand_from rollback" -s h -l help -d 'Print help'
complete -c blackship -n "__fish_blackship_using_subcommand snapshot; and __fish_seen_subcommand_from rollback" -s V -l version -d 'Print version'
complete -c blackship -n "__fish_blackship_using_subcommand snapshot; and __fish_seen_subcommand_from delete" -s h -l help -d 'Print help'
complete -c blackship -n "__fish_blackship_using_subcommand snapshot; and __fish_seen_subcommand_from delete" -s V -l version -d 'Print version'
complete -c blackship -n "__fish_blackship_using_subcommand snapshot; and __fish_seen_subcommand_from help" -f -a "create" -d 'Create a snapshot of a jail'
complete -c blackship -n "__fish_blackship_using_subcommand snapshot; and __fish_seen_subcommand_from help" -f -a "list" -d 'List snapshots for a jail'
complete -c blackship -n "__fish_blackship_using_subcommand snapshot; and __fish_seen_subcommand_from help" -f -a "rollback" -d 'Rollback a jail to a snapshot'
complete -c blackship -n "__fish_blackship_using_subcommand snapshot; and __fish_seen_subcommand_from help" -f -a "delete" -d 'Delete a snapshot'
complete -c blackship -n "__fish_blackship_using_subcommand snapshot; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c blackship -n "__fish_blackship_using_subcommand clone" -s h -l help -d 'Print help'
complete -c blackship -n "__fish_blackship_using_subcommand clone" -s V -l version -d 'Print version'
complete -c blackship -n "__fish_blackship_using_subcommand completion" -s h -l help -d 'Print help'
complete -c blackship -n "__fish_blackship_using_subcommand completion" -s V -l version -d 'Print version'
complete -c blackship -n "__fish_blackship_using_subcommand supervise" -s h -l help -d 'Print help'
complete -c blackship -n "__fish_blackship_using_subcommand supervise" -s V -l version -d 'Print version'
complete -c blackship -n "__fish_blackship_using_subcommand logs" -s n -l lines -d 'Number of lines to show' -r
complete -c blackship -n "__fish_blackship_using_subcommand logs" -s f -l follow -d 'Follow log output (like tail -f)'
complete -c blackship -n "__fish_blackship_using_subcommand logs" -s h -l help -d 'Print help'
complete -c blackship -n "__fish_blackship_using_subcommand logs" -s V -l version -d 'Print version'
complete -c blackship -n "__fish_blackship_using_subcommand help; and not __fish_seen_subcommand_from up down restart ps check setup init armada exec run cp rm console bootstrap releases network health build template expose ports unexpose cleanup export import snapshot clone completion supervise logs help" -f -a "up" -d 'Start jails (respecting dependencies)'
complete -c blackship -n "__fish_blackship_using_subcommand help; and not __fish_seen_subcommand_from up down restart ps check setup init armada exec run cp rm console bootstrap releases network health build template expose ports unexpose cleanup export import snapshot clone completion supervise logs help" -f -a "down" -d 'Stop jails (in reverse dependency order)'
complete -c blackship -n "__fish_blackship_using_subcommand help; and not __fish_seen_subcommand_from up down restart ps check setup init armada exec run cp rm console bootstrap releases network health build template expose ports unexpose cleanup export import snapshot clone completion supervise logs help" -f -a "restart" -d 'Restart jails'
complete -c blackship -n "__fish_blackship_using_subcommand help; and not __fish_seen_subcommand_from up down restart ps check setup init armada exec run cp rm console bootstrap releases network health build template expose ports unexpose cleanup export import snapshot clone completion supervise logs help" -f -a "ps" -d 'List jail status'
complete -c blackship -n "__fish_blackship_using_subcommand help; and not __fish_seen_subcommand_from up down restart ps check setup init armada exec run cp rm console bootstrap releases network health build template expose ports unexpose cleanup export import snapshot clone completion supervise logs help" -f -a "check" -d 'Validate configuration'
complete -c blackship -n "__fish_blackship_using_subcommand help; and not __fish_seen_subcommand_from up down restart ps check setup init armada exec run cp rm console bootstrap releases network health build template expose ports unexpose cleanup export import snapshot clone completion supervise logs help" -f -a "setup" -d 'System setup (PF firewall anchor, etc.)'
complete -c blackship -n "__fish_blackship_using_subcommand help; and not __fish_seen_subcommand_from up down restart ps check setup init armada exec run cp rm console bootstrap releases network health build template expose ports unexpose cleanup export import snapshot clone completion supervise logs help" -f -a "init" -d 'Initialize a new Jailfile in the current directory'
complete -c blackship -n "__fish_blackship_using_subcommand help; and not __fish_seen_subcommand_from up down restart ps check setup init armada exec run cp rm console bootstrap releases network health build template expose ports unexpose cleanup export import snapshot clone completion supervise logs help" -f -a "armada" -d 'Orchestrate multiple jails (like docker-compose)'
complete -c blackship -n "__fish_blackship_using_subcommand help; and not __fish_seen_subcommand_from up down restart ps check setup init armada exec run cp rm console bootstrap releases network health build template expose ports unexpose cleanup export import snapshot clone completion supervise logs help" -f -a "exec" -d 'Execute a command in a running jail'
complete -c blackship -n "__fish_blackship_using_subcommand help; and not __fish_seen_subcommand_from up down restart ps check setup init armada exec run cp rm console bootstrap releases network health build template expose ports unexpose cleanup export import snapshot clone completion supervise logs help" -f -a "run" -d 'Run a command in a new ephemeral jail (always cleans up when command exits)'
complete -c blackship -n "__fish_blackship_using_subcommand help; and not __fish_seen_subcommand_from up down restart ps check setup init armada exec run cp rm console bootstrap releases network health build template expose ports unexpose cleanup export import snapshot clone completion supervise logs help" -f -a "cp" -d 'Copy files between host and jail'
complete -c blackship -n "__fish_blackship_using_subcommand help; and not __fish_seen_subcommand_from up down restart ps check setup init armada exec run cp rm console bootstrap releases network health build template expose ports unexpose cleanup export import snapshot clone completion supervise logs help" -f -a "rm" -d 'Remove/destroy jails'
complete -c blackship -n "__fish_blackship_using_subcommand help; and not __fish_seen_subcommand_from up down restart ps check setup init armada exec run cp rm console bootstrap releases network health build template expose ports unexpose cleanup export import snapshot clone completion supervise logs help" -f -a "console" -d 'Open an interactive console in a running jail'
complete -c blackship -n "__fish_blackship_using_subcommand help; and not __fish_seen_subcommand_from up down restart ps check setup init armada exec run cp rm console bootstrap releases network health build template expose ports unexpose cleanup export import snapshot clone completion supervise logs help" -f -a "bootstrap" -d 'Bootstrap a FreeBSD release for jail creation'
complete -c blackship -n "__fish_blackship_using_subcommand help; and not __fish_seen_subcommand_from up down restart ps check setup init armada exec run cp rm console bootstrap releases network health build template expose ports unexpose cleanup export import snapshot clone completion supervise logs help" -f -a "releases" -d 'List or manage releases'
complete -c blackship -n "__fish_blackship_using_subcommand help; and not __fish_seen_subcommand_from up down restart ps check setup init armada exec run cp rm console bootstrap releases network health build template expose ports unexpose cleanup export import snapshot clone completion supervise logs help" -f -a "network" -d 'Network management'
complete -c blackship -n "__fish_blackship_using_subcommand help; and not __fish_seen_subcommand_from up down restart ps check setup init armada exec run cp rm console bootstrap releases network health build template expose ports unexpose cleanup export import snapshot clone completion supervise logs help" -f -a "health" -d 'Health check status and monitoring'
complete -c blackship -n "__fish_blackship_using_subcommand help; and not __fish_seen_subcommand_from up down restart ps check setup init armada exec run cp rm console bootstrap releases network health build template expose ports unexpose cleanup export import snapshot clone completion supervise logs help" -f -a "build" -d 'Build a jail from a Jailfile'
complete -c blackship -n "__fish_blackship_using_subcommand help; and not __fish_seen_subcommand_from up down restart ps check setup init armada exec run cp rm console bootstrap releases network health build template expose ports unexpose cleanup export import snapshot clone completion supervise logs help" -f -a "template" -d 'Template management'
complete -c blackship -n "__fish_blackship_using_subcommand help; and not __fish_seen_subcommand_from up down restart ps check setup init armada exec run cp rm console bootstrap releases network health build template expose ports unexpose cleanup export import snapshot clone completion supervise logs help" -f -a "expose" -d 'Expose a jail port to the host'
complete -c blackship -n "__fish_blackship_using_subcommand help; and not __fish_seen_subcommand_from up down restart ps check setup init armada exec run cp rm console bootstrap releases network health build template expose ports unexpose cleanup export import snapshot clone completion supervise logs help" -f -a "ports" -d 'List exposed ports'
complete -c blackship -n "__fish_blackship_using_subcommand help; and not __fish_seen_subcommand_from up down restart ps check setup init armada exec run cp rm console bootstrap releases network health build template expose ports unexpose cleanup export import snapshot clone completion supervise logs help" -f -a "unexpose" -d 'Remove all port forwards for a jail'
complete -c blackship -n "__fish_blackship_using_subcommand help; and not __fish_seen_subcommand_from up down restart ps check setup init armada exec run cp rm console bootstrap releases network health build template expose ports unexpose cleanup export import snapshot clone completion supervise logs help" -f -a "cleanup" -d 'Clean up a failed jail (remove leftover resources)'
complete -c blackship -n "__fish_blackship_using_subcommand help; and not __fish_seen_subcommand_from up down restart ps check setup init armada exec run cp rm console bootstrap releases network health build template expose ports unexpose cleanup export import snapshot clone completion supervise logs help" -f -a "export" -d 'Export a jail to an archive'
complete -c blackship -n "__fish_blackship_using_subcommand help; and not __fish_seen_subcommand_from up down restart ps check setup init armada exec run cp rm console bootstrap releases network health build template expose ports unexpose cleanup export import snapshot clone completion supervise logs help" -f -a "import" -d 'Import a jail from an archive'
complete -c blackship -n "__fish_blackship_using_subcommand help; and not __fish_seen_subcommand_from up down restart ps check setup init armada exec run cp rm console bootstrap releases network health build template expose ports unexpose cleanup export import snapshot clone completion supervise logs help" -f -a "snapshot" -d 'Manage jail snapshots'
complete -c blackship -n "__fish_blackship_using_subcommand help; and not __fish_seen_subcommand_from up down restart ps check setup init armada exec run cp rm console bootstrap releases network health build template expose ports unexpose cleanup export import snapshot clone completion supervise logs help" -f -a "clone" -d 'Clone a jail from a snapshot'
complete -c blackship -n "__fish_blackship_using_subcommand help; and not __fish_seen_subcommand_from up down restart ps check setup init armada exec run cp rm console bootstrap releases network health build template expose ports unexpose cleanup export import snapshot clone completion supervise logs help" -f -a "completion" -d 'Generate shell completion scripts'
complete -c blackship -n "__fish_blackship_using_subcommand help; and not __fish_seen_subcommand_from up down restart ps check setup init armada exec run cp rm console bootstrap releases network health build template expose ports unexpose cleanup export import snapshot clone completion supervise logs help" -f -a "supervise" -d 'Start the Warden supervisor to monitor and auto-restart jails'
complete -c blackship -n "__fish_blackship_using_subcommand help; and not __fish_seen_subcommand_from up down restart ps check setup init armada exec run cp rm console bootstrap releases network health build template expose ports unexpose cleanup export import snapshot clone completion supervise logs help" -f -a "logs" -d 'Tail logs from a running jail'
complete -c blackship -n "__fish_blackship_using_subcommand help; and not __fish_seen_subcommand_from up down restart ps check setup init armada exec run cp rm console bootstrap releases network health build template expose ports unexpose cleanup export import snapshot clone completion supervise logs help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c blackship -n "__fish_blackship_using_subcommand help; and __fish_seen_subcommand_from armada" -f -a "init" -d 'Initialize a new blackship.toml'
complete -c blackship -n "__fish_blackship_using_subcommand help; and __fish_seen_subcommand_from armada" -f -a "up" -d 'Start all jails (auto-builds if needed)'
complete -c blackship -n "__fish_blackship_using_subcommand help; and __fish_seen_subcommand_from armada" -f -a "down" -d 'Stop all jails'
complete -c blackship -n "__fish_blackship_using_subcommand help; and __fish_seen_subcommand_from armada" -f -a "build" -d 'Build jail images from Jailfiles'
complete -c blackship -n "__fish_blackship_using_subcommand help; and __fish_seen_subcommand_from armada" -f -a "ps" -d 'Show status of all jails'
complete -c blackship -n "__fish_blackship_using_subcommand help; and __fish_seen_subcommand_from armada" -f -a "config" -d 'Validate and show configuration'
complete -c blackship -n "__fish_blackship_using_subcommand help; and __fish_seen_subcommand_from releases" -f -a "list" -d 'List all bootstrapped releases (default)'
complete -c blackship -n "__fish_blackship_using_subcommand help; and __fish_seen_subcommand_from releases" -f -a "delete" -d 'Delete a bootstrapped release'
complete -c blackship -n "__fish_blackship_using_subcommand help; and __fish_seen_subcommand_from releases" -f -a "verify" -d 'Verify a bootstrapped release'
complete -c blackship -n "__fish_blackship_using_subcommand help; and __fish_seen_subcommand_from network" -f -a "create" -d 'Create a new network'
complete -c blackship -n "__fish_blackship_using_subcommand help; and __fish_seen_subcommand_from network" -f -a "destroy" -d 'Destroy a network'
complete -c blackship -n "__fish_blackship_using_subcommand help; and __fish_seen_subcommand_from network" -f -a "list" -d 'List all networks'
complete -c blackship -n "__fish_blackship_using_subcommand help; and __fish_seen_subcommand_from network" -f -a "attach" -d 'Attach a jail to a network'
complete -c blackship -n "__fish_blackship_using_subcommand help; and __fish_seen_subcommand_from network" -f -a "detach" -d 'Detach a jail from a network'
complete -c blackship -n "__fish_blackship_using_subcommand help; and __fish_seen_subcommand_from template" -f -a "list" -d 'List available templates'
complete -c blackship -n "__fish_blackship_using_subcommand help; and __fish_seen_subcommand_from template" -f -a "inspect" -d 'Inspect a template or Jailfile'
complete -c blackship -n "__fish_blackship_using_subcommand help; and __fish_seen_subcommand_from template" -f -a "validate" -d 'Validate a Jailfile'
complete -c blackship -n "__fish_blackship_using_subcommand help; and __fish_seen_subcommand_from snapshot" -f -a "create" -d 'Create a snapshot of a jail'
complete -c blackship -n "__fish_blackship_using_subcommand help; and __fish_seen_subcommand_from snapshot" -f -a "list" -d 'List snapshots for a jail'
complete -c blackship -n "__fish_blackship_using_subcommand help; and __fish_seen_subcommand_from snapshot" -f -a "rollback" -d 'Rollback a jail to a snapshot'
complete -c blackship -n "__fish_blackship_using_subcommand help; and __fish_seen_subcommand_from snapshot" -f -a "delete" -d 'Delete a snapshot'
