# [config]
# zfs_enabled = true
# zpool = "rpool"
# dataset = "blackship"
# data_dir = "/var/blackship"

# [[jails]]
# name = "db"
# release = "15.0-RELEASE"
# hostname = "db.home.lan"
# [jails.network]
# vnet = false
# bridge = "blackship0"
# ip = "192.168.1.20"
# gateway = "192.168.1.1"
# [jails.network.dns]
# nameservers = ["192.168.1.104"]  # DNS servers
# mode = "custom"                        # custom or inherit

[config]
data_dir = "/var/blackship"
zfs_enabled = true
zpool = "rpool"
dataset = "blackship"

[[jails]]
name = "web"
release = "15.0-RELEASE"
hostname = "web.local"

[jails.network]
vnet = true
bridge = "blackship0"
ip = "10.0.1.10"
gateway = "10.0.1.1"
